apiVersion: v1
kind: Service
metadata:
  name: guestbook-service
  labels:
    app: guestbook
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/path: "/metrics"
    prometheus.io/port: "5000"
spec:
  type: NodePort
  selector:
    app: guestbook
  ports:
    - port: 80
      targetPort: 5000
      nodePort: 30007
